const ActionTypes = {
  UPDATE_USER: 'UPDATE_USER',
  GET_USERS: 'GET_USERS',
  ADD_USER: 'ADD_USER',
  DEL_USER: 'DEL_USER',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DEL_PRODUCT: 'DEL_PRODUCT',
  ADD_CATEGORY: 'ADD_CATEGORY',
  GET_CATEGORY: 'GET_CATEGORY',
};

export default ActionTypes;
