const ActionTypes = {
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
  GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
  REQ_GET_USERS: 'REQ_GET_USERS',

  ADD_USER: 'ADD_USER',
  ADD_USER_RESPONSE: 'ADD_USER_RESPONSE',
  DEL_USER: 'DEL_USER',
  DEL_USER_RESPONSE: 'DEL_USER_RESPONSE',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DEL_PRODUCT: 'DEL_PRODUCT',
  ADD_CATEGORY: 'ADD_CATEGORY',
  GET_CATEGORY: 'GET_CATEGORY',
};

export default ActionTypes;
